### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by var3n1k** [tuffii/EESTEC-TGBot-client#5]
### Неавторизованные пользователи
- [x] Форма регистрации (промежуточная версия)
### Авторизованные пользователи
- [x] Боковое меню (неоптимизированная версия)
#### Профиль
- [x] Страница профиля (неоптимизированная версия)
- [x] Внешняя ссылка на личный профиль
- [ ] Внешняя ссылка на чужой профиль
#### Рейтинг
- [ ] Страница общего рейтинга
- [x] Внешняя ссылка на общий рейтинг
- [ ] Страница рейтинга внутри отдела
- [x] Внешняя ссылка на рейтинг внутри отдела
- [ ] Страница рейтинга внутри проекта
- [x] Внешняя ссылка на рейтинг внутри проекта
- [ ] Страница рейтинга между отделами
- [x] Внешняя ссылка на рейтинг между отделами
- [ ] Страница рейтинга между проектами
- [x] Внешняя ссылка на рейтинг между проектами
#### Пользователи
- [x] Страница пользователей (неоптимизированная версия)
- [x] Внешняя ссылка на страницу пользователей
- [x] Страница подтверждения заявок на регистрацию (неоптимизированная версия)
- [x] Страница подтверждения заявок на участие в проекте
#### Отделы
- [ ] Страница текущих отделов (неоптимизированная версия)
- [ ] Внешняя ссылка на страницу текущих отделов
- [ ] Страница новых отделов (неоптимизированная версия)
- [ ] Страница архивных отделов (неоптимизированная версия)
#### Проекты
- [x] Страница текущих проектов
- [x] Внешняя ссылка на страницу текущих проектов
- [x] Страница новых проектов
- [x] Страница архивных проектов
#### Мероприятия
- [ ] Страница текущих мероприятий
- [ ] Внешняя ссылка на страницу текущих мероприятий
- [ ] Страница новых мероприятий
- [ ] Страница архивных мероприятий
#### Пользователи
- [ ] Интерфейс назначения роли администратора
#### Отделы
- [ ] Страница создания нового отдела
#### Проекты
- [x] Страница создания нового проекта
#### Мероприятия
- [ ] Страница создания нового мероприятия
